export { default as Text } from './Text'
export { default as View } from './View'
export { default as Btn } from './Btn'
export { default as TextInput } from './TextInput'
export { default as Centered } from './Centered'
